version: '3.8'
services:
  db:
    image: postgres:13-alpine
    container_name: nestjs_postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build: .
    container_name: nestjs_app
    environment:
      DATABASE_URL: postgres://username:pass@db:5432/database
    ports:
      - '3333:3333'
    depends_on:
      - db

volumes:
  postgres_data:
