### POST /bookmarks : create a bookmark
POST http://localHost:3333/bookmarks HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoidGVzdDJAZmFrZS5jb20iLCJpYXQiOjE3MjU3ODk4NDgsImV4cCI6MTcyNTc5MDc0OH0.2UQL7p0HB_huC4L3G0MeMIcj_DCcD6hmrSIWWSIn8DA
Content-Type: application/json

{
  "link":"yahoo.com",
  "title":"yahoo",
  "description":"web search"
}


###
GET http://localHost:3333/bookmarks/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoidGVzdDJAZmFrZS5jb20iLCJpYXQiOjE3MjU3ODk4NDgsImV4cCI6MTcyNTc5MDc0OH0.2UQL7p0HB_huC4L3G0MeMIcj_DCcD6hmrSIWWSIn8DA