
### sing up 
POST http://localHost:3333/auth/signup HTTP/1.1
Content-Type: application/json

{
  "email":"test2@fake.com",
  "password": "pass",
  "id":15
}

### sing in
POST http://localHost:3333/auth/signin HTTP/1.1
Content-Type: application/json

{  
  "email":"test2@fake.com",
  "password": "pass"
}
